# Generated by Django 5.2.5 on 2025-08-23 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('created_at', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ada_bill',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_sentiment', models.CharField(blank=True, choices=[('support', 'Support'), ('oppose', 'Oppose'), ('suggest', 'Suggestion'), ('neutral', 'Neutral')], max_length=10)),
                ('ai_sentiment', models.CharField(blank=True, choices=[('support', 'Support'), ('oppose', 'Oppose'), ('suggest', 'Suggestion'), ('neutral', 'Neutral')], max_length=10, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ada.bill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ada_feedback',
            },
        ),
    ]
