# Generated by Django 5.2.5 on 2025-08-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ada', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='sentiment',
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ai_sentiment',
            field=models.CharField(blank=True, choices=[('support', 'Support'), ('oppose', 'Oppose'), ('suggest', 'Suggestion'), ('neutral', 'Neutral')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_sentiment',
            field=models.CharField(blank=True, choices=[('support', 'Support'), ('oppose', 'Oppose'), ('suggest', 'Suggestion'), ('neutral', 'Neutral')], max_length=10, null=True),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='ada_feedback',
        ),
    ]
